### ISSUE TITLE
加入讚和轉貼按鈕

### ISSUE THREAD

**Issue by ryudoawaru** [rubytaiwan/rubyconftw2015#24]
加入：
1.  FB的贊
2.  Twitter  轉貼

兩個 button，該放哪裡請 Rice 協助

**Comment by ninayeh** [comment]
@ricetseng 請協助提供兩個button所放置的位置

**Comment by ricetseng** [comment]
<img width="222" alt="social" src="https://cloud.githubusercontent.com/assets/1342788/8692009/6ce4cd0a-2afc-11e5-8813-b93e1fdae502.png">
