### ISSUE TITLE
footer 矮人礦坑的矮人糊糊的，每個矮人要可以hover 顯示工作人員

### ISSUE THREAD

**Issue by ricetseng** [rubytaiwan/rubyconftw2015#34]
![2015-07-14 12 14 02](https://cloud.githubusercontent.com/assets/1342788/8654515/52fc0754-29bd-11e5-8bcf-d6fc4837eec6.png)

**Comment by ryudoawaru** [comment]
請 @ricetseng 提供：
-  妳和康橋的資訊
-  如果超過四個人，其他人要擺在哪

**Comment by ricetseng** [comment]
把小人縮小，需要知道最後會放幾人

我的資訊：Rice Tseng/ UX Designer / www.ricetseng.com

康橋：KangChiao/Illustrator &Animator /http://kangchiao.wix.com/kangchiao

**Comment by ricetseng** [comment]
<img width="712" alt="footer" src="https://cloud.githubusercontent.com/assets/1342788/8691599/9544c980-2af7-11e5-85b7-de684e350d29.png">

**Comment by ryudoawaru** [comment]
1.  Me
2.  龍哥
3.  Rice
4.  康橋
5.  Nina
6.  蒼時

應該要做一個 modal 顯示最後包括現場的 staff 們

**Comment by ricetseng** [comment]
![footer2](https://cloud.githubusercontent.com/assets/1342788/8724500/99d263ca-2c02-11e5-9c94-e02d6bf5ee35.png)
![footer](https://cloud.githubusercontent.com/assets/1342788/8724502/99d4c02a-2c02-11e5-9c04-07508bac0d40.png)

**Comment by ricetseng** [comment]
dwart_group link 
https://drive.google.com/open?id=0B4S2hHoiyHsWZHhnWURfMzVXcUk
