### ISSUE TITLE
imac 27寸顯示問題：紅色圈起來的是很模糊的部分

### ISSUE THREAD

**Issue by ricetseng** [rubytaiwan/rubyconftw2015#52]
![blur](https://cloud.githubusercontent.com/assets/1342788/8691692/b6e9ee34-2af8-11e5-9f6a-d438436c5598.png)

**Comment by ryudoawaru** [comment]
@ricetseng 這些圖在昨天給的 zip 都有吧

**Comment by ricetseng** [comment]
恩恩 對唷 svg zip都有 或是需要 x2 and x1

**Comment by elct9620** [comment]
![](https://cloud.githubusercontent.com/assets/1342788/8691692/b6e9ee34-2af8-11e5-9f6a-d438436c5598.png)

這張出來的圖原本就是糊的。

另外兩張我不確定出現在哪裡就沒有做 Retian 的處理。

**Comment by ryudoawaru** [comment]
請 @ricetseng 看一下還有沒有沒加到的地方？

**Comment by ricetseng** [comment]
我upload 新的到slack
