### ISSUE TITLE
scroll down fade in interaction 

### ISSUE THREAD

**Issue by ricetseng** [rubytaiwan/rubyconftw2015#59]
demo(後半段scroll down每個內容fade in 的感覺 ) : https://drive.google.com/open?id=0B4S2hHoiyHsWTFRNaUg4NXdsU1k

reference（scroll down 的時候，每個content 會fade in） : https://www.jsconfar.com/

**Comment by ryudoawaru** [comment]
ㄟ　這會回到 section 要不要滿版的問題，你 show 的影片　是假定每 section 都滿版的狀況，不滿版的話沒辦法玩這效果

**Comment by ricetseng** [comment]
我show的影片不是demo滿版效果，是fade in 順序。如同jsConf scroll down fade in 的感覺
